CREATE DATABASE IF NOT EXISTS ELETRODOMESTICOS_SAEP_DB;
USE ELETRODOMESTICOS_SAEP_DB;

CREATE TABLE USUARIO (
    USU_ID INT AUTO_INCREMENT PRIMARY KEY,
    USU_NOME VARCHAR(255) NOT NULL,
    USU_EMAIL VARCHAR(255) UNIQUE NOT NULL,
    USU_SENHA VARCHAR(255) NOT NULL
);

CREATE TABLE LOG (
    LOG_ID INT AUTO_INCREMENT PRIMARY KEY,
    LOG_DESCRICAO VARCHAR(255),
    LOG_DATA_HORA DATETIME DEFAULT CURRENT_TIMESTAMP,
    FK_USU_ID INT,
    FOREIGN KEY (FK_USU_ID) REFERENCES USUARIO(USU_ID)
);

CREATE TABLE ELETRODOMESTICO (
    ELETRODOMESTICO_ID INT AUTO_INCREMENT PRIMARY KEY,
    ELETRODOMESTICO_NOME VARCHAR(255) NOT NULL,
    ELETRODOMESTICO_QTD_ESTOQUE INT DEFAULT 0,
    ELETRODOMESTICO_FORNECEDOR VARCHAR(255),
    ELETRODOMESTICO_CATEGORIA VARCHAR(255),
    ELETRODOMESTICO_POTENCIA FLOAT,
    ELETRODOMESTICO_CONS_ENER FLOAT,
    ELETRODOMESTICO_GARANTIA VARCHAR(255),
    ELETRODOMESTICO_PRIOR_REP VARCHAR(255),
    FK_USU_ID INT,
    FOREIGN KEY (FK_USU_ID) REFERENCES USUARIO(USU_ID)
);

CREATE TABLE ESTOQUE (
    ESTOQUE_ID INT AUTO_INCREMENT PRIMARY KEY,
    ESTOQUE_QTD INT NOT NULL,
    FK_ELETRODOMESTICO_ID INT,
    FOREIGN KEY (FK_ELETRODOMESTICO_ID) REFERENCES ELETRODOMESTICO(ELETRODOMESTICO_ID)
);
